### ISSUE TITLE
I cannot see the menu

### ISSUE THREAD

**Issue by XXGisterXX** [DarkSnakeGang/GoogleSnakeModLoader#1]
Here (Btw, I'm French) : 

https://user-images.githubusercontent.com/106403204/223708850-df4996c2-2f65-4049-b6d1-deaabcaf6f63.mp4

**Comment by hwatson381** [comment]
![image](https://user-images.githubusercontent.com/69080709/223805833-c2aa872b-da6c-4f9d-b735-1b05bdce3573.png)

Can you click on tampermonkey and show what this menu looks like?

Also try on https://www.google.com/fbx?fbx=snake_arcade

If you have the fbx version it will only be active on that page and not google search.

If you want it on google search then you need the standard version (2nd link in table).

**Comment by XXGisterXX** [comment]
Here : 
![image](https://user-images.githubusercontent.com/106403204/224549759-a0ec8496-566a-48b8-b06e-9ac4740c90d1.png)

**Comment by XXGisterXX** [comment]
nope,dosent work... this is garbage cause i tried everything... here is my discord. : The Killer 1223#7273

**Comment by hwatson381** [comment]
I sent you a friend req on discord
