### ISSUE TITLE
Can you do this without Tampermonkey?

### ISSUE THREAD

**Issue by clarkni1** [DarkSnakeGang/GoogleSnakeModLoader#10]
Say Tampermonkey crashed or something or it isn't available to someone. Could you make it more versatile and make it so that it can run on different extensions?

**Comment by hwatson381** [comment]
Violentmonkey should also work, we just recommend tampermonkey as it's much more well known. https://violentmonkey.github.io/

It doesn't work on greasemonkey, but that's firefox only and there's more important stuff to fix as firefox users can get tampermonkey instead.
