### ISSUE TITLE
Doesn't work on mobile

### ISSUE THREAD

**Issue by i-cm** [DarkSnakeGang/GoogleSnakeModLoader#14]

**Comment by hwatson381** [comment]
Haven't tested myself, but it might work on mobile with kiwi browser + requesting desktop site. What did you try?

**Comment by Yarmiplay** [comment]
We need feedback of what was actually attempted or some details. After testing myself, Kiwi and desktop site still work, so I'm closing this.

**Comment by i-cm** [comment]
[Visit Google snake mod in mobile](https://i-cm.github.io/google-snake/)
I tried to make it

**Comment by hwatson381** [comment]
Ah this is a cool idea, might be useful for people who can't get the extension to work for other reasons. You could do something similar to how archive.org does it where you host all the scripts/resources on your website, and then you'd just add in the script for the modloader.

**Comment by Windowszin** [comment]
just use puffin browser and intall tampermonkey

**Comment by PatoFlamejanteTV** [comment]
pls close the issue

**Comment by hwatson381** [comment]
Possible now. See here https://googlesnakemods.com/ (mods built into a website so doesn't need tampermonkey)
