### ISSUE TITLE
Can you reply with the mod code as a bookmarklet?

### ISSUE THREAD

**Issue by bogusbobuk** [DarkSnakeGang/GoogleSnakeModLoader#15]
My school blocked being able to download javascript and html files so I cant download the file, and they also blocked extensions so I'm not able to download tampermonkey. Could you possibly reply to this with the full userscript edited code for me please? i'm sorry if this is confusing to you, i'm not experienced with github besides copying a file to bookmarks bar LOL.
![Screenshot 2023-05-23 8 46 37 AM](https://github.com/DarkSnakeGang/GoogleSnakeModLoader/assets/134395820/db60f879-ab0b-4929-b1fe-cc653cb6d89b)

**Comment by hwatson381** [comment]
Sorry not possible, more info here https://github.com/DarkSnakeGang/GoogleSnakeModLoader/blob/main/docs/why_not_bookmarks.md

**Comment by TheMasterCoders** [comment]
Can somebody close this?
