### ISSUE TITLE
Code not found

### ISSUE THREAD

**Issue by KarmaDrumSticks** [DarkSnakeGang/GoogleSnakeModLoader#18]
I just downloaded the mod and it says code not found, I have the latest version so I don't know what to do

**Comment by hwatson381** [comment]
> I just downloaded the mod and it says code not found, I have the latest version so I don't know what to do

Just saw this. Is it still happening? It means it can't find the code for google snake, so either you had very slow internet (so snake code didn't load in time), or maybe google made some changes to where the snake code is located. If it's still happening, you could join the google snake discord and leave a comment in #snake-modding where it's easier for us to help https://discord.gg/NA6vHg62An

**Comment by zf5k5d8ymk-maker** [comment]
Testing out fonts###

**Comment by zf5k5d8ymk-maker** [comment]
_testing out fonts_
