### ISSUE TITLE
"Code not found after 4 seconds"

### ISSUE THREAD

**Issue by faqzs** [DarkSnakeGang/GoogleSnakeModLoader#19]
happens for all mods, im using the fbx, and im on latest version

**Comment by hwatson381** [comment]
> happens for all mods, im using the fbx, and im on latest version

Hey, thanks for reporting. I can't seem to reproduce though, what was the exact fbx link? https://www.google.com/fbx?fbx=snake_arcade was it .com or something else? Are you still getting the issue? Could you send a screenshot of your sources panel (in chrome do ctrl+shift+i then click on sources)? Also if you want, you could join the google snake discord where it's easier to help you. https://discord.gg/NA6vHg62An

In the past, people have received this error when google were running an experiments and a small percentage of user would get a slightly different version of google snake.
