### ISSUE TITLE
More mod menu, Pudding, More Pudding And Visibility Are Not Working

### ISSUE THREAD

**Issue by BenjaminOfYoutube** [DarkSnakeGang/GoogleSnakeModLoader#21]
when i open the mod, it didnt work, i tried alternative versions but it didnt worked well, even if i reload didnt work, except for level editor and mouse mode, here some mods that are not working:

![Captura de tela 2023-10-07 113939](https://github.com/DarkSnakeGang/GoogleSnakeModLoader/assets/147259678/0ecb89da-ce8d-49da-8658-dd8bd9047179)
![Captura de tela 2023-10-07 113955](https://github.com/DarkSnakeGang/GoogleSnakeModLoader/assets/147259678/7d600848-fd1d-4f31-a548-997f8898fee1)
![Captura de tela 2023-10-07 114015](https://github.com/DarkSnakeGang/GoogleSnakeModLoader/assets/147259678/7de88070-87e0-4bb8-868a-a63a081e7626)
![Captura de tela 2023-10-07 114024](https://github.com/DarkSnakeGang/GoogleSnakeModLoader/assets/147259678/e09d15ee-24ce-4f49-92a4-afe8a1ceae10)

**Comment by BenjaminOfYoutube** [comment]
So what to _do?****_

**Comment by BenjaminOfYoutube** [comment]
_**so_ _what_ _to_ _do?**_

**Comment by BenjaminOfYoutube** [comment]
**so what to do now?**

**Comment by Yarmiplay** [comment]
We are aware, just wait until we fix it, thanks. Pudding fix coming soon.
