### ISSUE TITLE
Code not found after 4 seconds

### ISSUE THREAD

**Issue by gamingagent80** [DarkSnakeGang/GoogleSnakeModLoader#27]
I have tried updating the script for both the fbx and standard version separately but nothing seems to work. Changing the background color still works though. I am using Firefox Bata v.122.0b3 (64-bit) on a Windows-PC.  As don't know the specifics of how the mod loader works I am unable to provide any further detail that I think would be helpful to fixing this bug. GL

**Comment by hwatson381** [comment]
What's page are you playing Google Snake on? There's the standalone page https://www.google.com/fbx?fbx=snake_arcade and there's also the search page (where you do a google search for "google snake"). Also it's possible it could make a difference if you aren't on ".com". Another thing to check would be whether you have other extensions installed that might interfere with modloader.

**Comment by hwatson381** [comment]
Not sure whether it will solve your issue, but we now have a separate website with mods built in now which could work. https://googlesnakemods.com/

**Comment by gamingagent80** [comment]
I'm sorry it took me so long to reply. The issue seemed to be gone after I tried opening the page in private mode which lead me to believe that an extension I had previously installed must be causing the problem. However that appeared to magically fix the problem I was having. The new, separate website worked fine as well. Thank you for the quick response and have nice day!
