### ISSUE TITLE
can you make a bookmark version like the old ones

### ISSUE THREAD

**Issue by Gabriella4a** [DarkSnakeGang/GoogleSnakeModLoader#3]
annoying that they dont work

**Comment by hwatson381** [comment]
Not possible :/

And I agree it's not ideal having to install an extension for this, but there's no other way of doing it.

There's a more detailed explanation here:
https://github.com/DarkSnakeGang/GoogleSnakeModLoader/blob/main/docs/why_not_bookmarks.md

**Comment by Yarmiplay** [comment]
sadly can't be helped
