### ISSUE TITLE
Assets not loading

### ISSUE THREAD

**Issue by X-man888** [DarkSnakeGang/GoogleSnakeModLoader#31]
On the website, most additional assets won't load, this means that you can't load the additional speeds, apple totals, chess pieces, or custom poison fruit textures.

**Comment by Yarmiplay** [comment]
Screenshot? Also if you show console that could help

**Comment by X-man888** [comment]
<img width="365" alt="image" src="https://github.com/user-attachments/assets/6632afe1-2d44-4d71-9cf6-2cd88176d20e">
this is a picture of the menu, if it is an image not in normal snake (exception is levels in level editor), it will show up as the 3rd and 4th rows in the menu, or gone in normal gameplay.

How do you show the console?

**Comment by X-man888** [comment]
I am on a school thing and they block postimg. Thanks for helping out!
