### ISSUE TITLE
can you fix the tampermonkey snake mod loader

### ISSUE THREAD

**Issue by C1intOn110309** [DarkSnakeGang/GoogleSnakeModLoader#5]
ive downloaded every userscript on the mod, it won't work on it. ive enabled it and it doesn't work(im not using greasemonkey)

**Comment by hwatson381** [comment]
Hey, can you give some more details - what browser are you using? Do you see any error messages? Does it show the indicator in the bottom right?

**Comment by C1intOn110309** [comment]
Im using Google, No error messages, No indicator on the bottom right, the mod is enabled, and the mod doesn't activate

**Comment by hwatson381** [comment]
Can you give a screenshot of what tampermonkey mods are currently running (looks like this)
![image](https://user-images.githubusercontent.com/69080709/230684318-6df6f8fb-4606-42c5-8cf9-995579bbc98a.png)

Also, could you try on https://www.google.com/fbx?fbx=snake_arcade

If you have discord, it might be easier to add me there so it's easier for me to help Llama#8640

**Comment by C1intOn110309** [comment]
![Evidence2](https://user-images.githubusercontent.com/95944519/233749130-3fa98913-7dc6-4dca-bdd5-f2c7be0ae631.png)

**Comment by C1intOn110309** [comment]
![eVIDENCE](https://user-images.githubusercontent.com/95944519/233749158-95d62e36-0379-4cb2-b210-308cc9556c39.png)

**Comment by hwatson381** [comment]
Thanks for the screenshot. I think this might happen if you have _really_ slow internet, so the page isn't sufficiently loaded by the time the mods can run. Will have a look to see if there is a way to fix this.

**Comment by hwatson381** [comment]
This was a tricky one to figure out, thanks for reporting it as I'm sure lots of other people would've been affected by it as well, but not bothered to report it.

Go to the dashboard
![image](https://user-images.githubusercontent.com/69080709/233854682-807d653a-3b01-4f9e-b16d-9cfccdef4c89.png)

Then click on the mod and go to it's settings. Then change "run at" to be document-body
![image](https://user-images.githubusercontent.com/69080709/233854752-79e56cb3-2463-4f32-b5b7-d03a283db604.png)

In the next update of the mod I'll fix this for everyone, but for now you can do the above steps.
