### ISSUE TITLE
no tampermonkey

### ISSUE THREAD

**Issue by ainzy02** [DarkSnakeGang/GoogleSnakeModLoader#6]
is their someway i can use this without tampermonkey or downloading anything I have a restricted Chromebook

**Comment by hwatson381** [comment]
hmm seems tricky.
You could try downloading tampermonkey in this way https://www.wikihow.com/Add-Blocked-Extensions-in-Google-Chrome

I've never used a chromebook before so I'd be very curious to know if this works.

**Comment by ainzy02** [comment]
it doesnt work but thanks you anyways

**Comment by hwatson381** [comment]
Ok, it's probably not possible to do then :/
