### ISSUE TITLE
The Dice mod is broken.

### ISSUE THREAD

**Issue by Dorian4771** [DarkSnakeGang/GoogleSnakeModLoader#7]
That's it.

**Comment by hwatson381** [comment]
Thanks for reporting this. Currently, some people are getting a different version of snake where dice mod and more menu mod don't work. There is a workaround, but it doesn't always fix it. See here https://github.com/DarkSnakeGang/GoogleSnakeModLoader/blob/main/docs/different_version.md

**Comment by Yarmiplay** [comment]
@Dorian4771 if the earlier comment suggestion doesn't fix it for you, please comment here to let me know, I generally don't plan on fixing dice mod until google's experimental version of snake comes out officially.
