### ISSUE TITLE
Google snake won't open!

### ISSUE THREAD

**Issue by sindisaoa** [DarkSnakeGang/GoogleSnakeModLoader#8]
I downloaded the mod with tamper monkey, searched up google snake, activated the mod, tried to press play but it just stayed the same! i activated the fbx version and the screen was straight green. any help?

**Comment by hwatson381** [comment]
This can happen if you have more than one version running at once. Can you click on the tampermonkey extension to see what mods are running. If you can see more than one google snake mod running then you should remove the extra one.

![image](https://user-images.githubusercontent.com/69080709/231289291-653ea536-8970-49a0-9c13-19e36c8e6bf2.png)

If this doesn't fix it, then it could be a new issue, in which case you should take a screenshot of the developer console and send a screenshot of any messages it has. On chrome you can get to the developer console by pressing ctrl+shift+j
