### ISSUE TITLE
my google snake wont open for some reason

### ISSUE THREAD

**Issue by noisymilo132** [DarkSnakeGang/GoogleSnakeModLoader#9]
im using chrome i see the popup in the bottom left asking what mods i want but it will only open when i have "none" selected i only have one of the mod loader things on tamper monkey enabled and it just wont let me start

**Comment by noisymilo132** [comment]
i fixed this somhow by just spamming the start button

**Comment by hwatson381** [comment]
Do you get this consistently when using mouse mode? What url are you playing snake on? If possible, could you give a screenshot of the developer console (ctrl+shift+j on chrome)
